### ISSUE TITLE
Blacken to also pick up `{.python}` code-blocks

### ISSUE THREAD

**Issue by maxschulz-COL** [adamchainz/blacken-docs#357] opened 2024-07-30 08:58 UTC
### Package Version

1.18.0

### Description

First of all really useful package, thanks!

So here is the issue: We discovered that while the tool can pick up a block like:

```python
```python
def foo():
  return "poo"
\```

```

it does not pick up on the equivalent `{.python}` syntax (which allows to specify further options: https://python-markdown.github.io/extensions/fenced_code_blocks/).

We are trying to use this in mkdocs documentation, where the codeblocks carry further options, so cannot be specified as ` ```python `.

Would this be something that could be supported? 

Tagging also @maartenbreddels for visibility.

**Comment by adamchainz** [comment] 2024-07-30 11:58
Dupe of #274 / #281.

Since you’re another report, I think we could consider adding support. The next step would be to rebase and finish up the work for #274 (docs, changelog note, more tests).

**Closed by adamchainz** 2024-07-30 11:58 UTC
